language: node_js
node_js:
  - '10'

before_script:
  - yarn install
script:
  - yarn build

# install our .npmrc system-wide
before_deploy:
  - cp .npmrc-publish ~/.npmrc
deploy:
  provider: script
  script: npx lerna publish -y from-git
  skip_cleanup: true
  on:
    tags: true
    branch: master
