language: node_js
node_js:
  - '10'
# install newest yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install
script:
  - yarn build
  - yarn typecheck
  - yarn test
  - yarn coveralls

deploy:
  provider: script
  script: yarn semantic-release
  skip_cleanup: true
  on:
    branch: master
