language: node_js
node_js:
  - '10'
env:
  - GK_LOCK_YARN_OPTS='-W'

# install newest yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install -g codecov
before_script:
  - yarn install --frozen-lockfile
script:
  - yarn build
  - yarn typecheck
  - yarn lint --debug
  - yarn test:coverage
  - yarn bundlesize

after_success:
  - codecov

deploy:
  provider: script
  script: yarn semantic-release
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
    - master
    - /^greenkeeper/.*$/
