name: Publish to NPM registry

on: 
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn semantic-release
      