name: Validate Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add codecov
    - run: yarn install --frozen-lockfile
    - run: yarn typecheck
    - run: yarn lint
    - run: yarn build
    - run: yarn test:coverage
    - run: yarn bundlesize
      env:
        CI: true