name: Validate Pull Request

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    env:
        CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn typecheck
    - run: yarn lint
    - run: yarn build
    - run: yarn test:coverage
    - run: yarn bundlesize
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      